name: build for segfault vps

on:
  workflow_dispatch:

jobs:
  build-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main

      - uses: actions/setup-go@main
        with:
          go-version: "^1.13.1"

      - run: go mod tidy

      - run: CGO_ENABLED=0 go build

      - uses: softprops/action-gh-release@master
        with:
          files: sfwg
